---
title: "temp"
author: "Subhrajyoty Roy"
date: "April 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

## R Python Conversion

```{python}
from pynitefields import * 
import numpy as np

def genMOLS(p, r=1, poly=None):
    """
    In this function,
    p = prime
    r = power of the prime
    poly = coefficients of the field generating polynomial as a list
    
    DEMO EXAMPLE:
    genMOLS(2,  3, [1, 1, 0, 1])
        creates the finite field of order 2^3 = 8 with the irreducible 
        polynomial given by 1 + x + x^3, note that the coefficients are
        in increasing power of exponents of x.
    """
    if (r != 1):
        if poly == None:
            print('Error! Please enter the generating polynomial')
        else:
            gf = GaloisField(p, r, poly)
    else:
        gf = GaloisField(p)
    MOLS = []
    v = p**r
    for u in range(1, v):
        LS = []
        for i in range(v):
            for j in range(v):
                x = (gf[i] * gf[u]) + gf[j]
                LS.append(x.prim_power)
        MOLS.append(LS)
    
    return(MOLS)

x = genMOLS(p = 3, r = 2, poly = [2, 1, 1])
print(x)
```


Print them in R.

```{r}


```






